# Generated by Django 3.2.15 on 2022-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
